# Generated by Django 5.2.4 on 2025-07-28 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='mobile',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='patient',
            name='mobile',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
